baseurl: "https://www.alpescraft.fr/"
title: "AlpesCraft"
canonifyurls: true

params:
  # Conference info
  Name: "AlpesCraft"
  Year: "2022"
  Description: "D√©couvrir, apprendre et se perfectionner"
  Date: "Les 9 et 10 Juin 2022"
  Venue: "Alpexpo"
  Address: "2 Av. d'Innsbruck"
  City:  "Grenoble"
  State: "France"
  Twitter: "https://twitter.com/AlpesCraft"
  Email: "contact@alpescraft.fr"
  images:
    - "/img/logo/color/03-AlpesCraft_Couleurs-M.png"

  Credits:
    - name: "Xavier Nopre"
      url: "https://twitter.com/xnopre"
    - name: "Headway"
      url: "https://unsplash.com/photos/5QgIuuBxKwM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
    - name: "Fancycrave"
      url: "https://unsplash.com/photos/yB5cYEq7y2U?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - home
    - about
    - sponsors
    - partners
    - schedule
    - billetterie
    - location

  # Titles which you can translate to other languages
  Titles:
     home:
       - title: "La conf√©rence"
         icon: "icon-home"
     about:
       - title: "√Ä propos"
         icon: "icon-info"
     location:
       - title: "Nous rejoindre"
         icon: "icon-location-pin"
     speakers:
       - title: "Speakers"
         icon: "icon-speech"
     schedule:
       - title: "Programme"
         icon: "icon-book-open"
     sponsors:
       - title: "Sponsors"
         icon: "icon-star"
     partners:
       - title: "Partenaires"
         icon: "icon-heart"
     billetterie:
       - title: "Billetterie"
         icon: "icon-basket"
     edition2019:
       - title: "√âdition 2019"
         icon: "icon-control-rewind"

  Previous:
    - edition2019
    - edition2021

  TitlesPrevious:
    edition2019:
       - title: "2019"
         icon: "icon-control-rewind"
    edition2021:
      - title: "2021"
        icon: "icon-control-rewind"

  LinksPrevious:
    edition2019: "edition_2019"
    edition2021: "edition_2021"

  # Icones
  Icones:
    grid:
      - title: "D√©couvrir"
        icon: "icon-question"
        text: "Venez d√©couvrir ce qui se cache derri√®re le Software Craftsmanship"
      - title: "Apprendre"
        icon: "icon-layers"
        text: "Un lieu d'apprentissage et de partage afin de progresser pour produire des logiciels toujours meilleurs"
      - title: "Se perfectionner"
        icon: "icon-check"
        text: >
              √âchanger avec des professionels lors d'une seconde journ√©e en partenariat avec
              <a href='https://socrates-fr.github.io/'' target='_blank'>SoCraTes-FR</a>
    description:
      - paragraph: "AlpesCraft est une conf√©rence technique, agnostique aux technologies"
      - paragraph: "Nous pensons que le plus important est de bien ma√Ætriser les fondamentaux et d'apprendre les pratiques au-del√† des frameworks"
      - paragraph: >
                   Peu importe votre langage de programmation, votre framework ou librairie pr√©f√©r√©,
                   participer √† Alpescraft c'est apprendre des choses applicables d√®s le lendemain

  # About
  About:
    - title: "D√©couvrir"
      img: "https://lh3.googleusercontent.com/syzh0Z4UheYfgNWWqXIRtf3qNbC3wg7PVjrLEUXeyaYSEd90FholLBAkFf8BFAdqF-VPdbrcxXj6EA-lSsISmMj3BI0fA6mj_PA8_wnvZEkrwsvA5cNctTw3lyeSCrP1nlX-O-OnEz-0JjZ9_UWBjVM9qUOjYt_Te3fi_UGXYz0ZtPWK3c46lz9aZau-h2zmJq17aPvFl6WU11iPUZ8pTMZMHapSlUljWapr6aQA40eerCTfWxAjso0Bl4jyFxr54c2QU5QDzzrzmKf1LgfaTMwr3aWsjMbLZ1h-iClqtD6MNdCvJPFmd7EiruXvMqjGfiET6XztuwNf6I6dMDlbD5kJHYABBbI_L9dxn8st-icg0j29By1aThIFhs_WvqXa-ERnIhbKXRgKgTQY0h4XbbblO9krRbKoNSVrKIMQ8RANl1KIlcZ5irl6GiqrOXYd6yHQxC2xl0nqlMlPOe1-x0_W6adCMSz9zmMttCVf0Q-W3R99JtWpScE0LG3sHOwAbsg6mBQ6QQoEpTftBdEwtS6vyNMqNiNIDs7lItTsr_OwyCmLK1OP8t5vyNs5ZafjuryHe0YEGhF9KrcIPyHYi9GOYf_hEDFZraDblBeu68yVY3DxpbZ0lmoT_3T_vBj10r9VA5ZPDPPk5W66clnZvxlmrix4p2JlIC-qE3VZbX2v0Iq1EYTq-MYxTDmtoC_k5gjCoQMeqGW8SIzf5vDEUh6cm5yiMzpnzx9UGJXV4GPmMJQ=w1247-h936-no"
      imgInRightSide: true
      text:
        - paragraph: "R√©aliser un produit logiciel qui correspond aux besoins de nos utilisateurs et qui soit facile √† faire √©voluer est un Graal difficile √† atteindre."
        - paragraph: >
                      Cela demande √† la fois une excellence technique, une ma√Ætrise des bonnes pratiques sur l'ensemble de la cha√Æne de production,
                       des comp√©tences de coop√©ration et de communication avec l'ensemble des acteurs, un paradigme de travail d'apprentissage (The Build-Measure-Learn Feedback Loop)...
                       Une qu√™te passionnante qui est facilit√©e lorsqu'on rencontre des personnes exp√©riment√©es qui nous guident sur les chemins √† suivre et nous aident √† nous am√©liorer.
    - title: "Apprendre"
      img: "https://lh3.googleusercontent.com/NojKLuH79Y9qQ_vhGGvbmzqq9w2XwFMkgdRft0sx_NnaHn3S43m1sI2WlUB8M__HSWFEVqp-p6VrzAFMuh8pPzN7n57MyC6-vbDjexf28MvOGiYVHnoA8RR2xnIDzQ2CvJf_vVk_se7Gi2zY_YeeJJc3RFjyfYVYM_GarYHqUy5iGr-FImsJOlYo5cKJOfV12wOkThewxGd5076Dd5FD04qq8L8fYTCNTYv-HfEBG1S93iJwmPgIv20aDkAHo0Rkk8GKG2QpvwZYQD698UT894dgxb-8Pl9x5dHNA066XMAFZbtciHheWsFmwL0lPkCrTG2iGRelPWkeNcoTdx3Ss1zWUOXPYjwbMtANKhfGk0C9Dew0ud2w1xDSLbQW9Zm33nyRVZPtcqwMmcXXW0ifYmHnEsB6j3Wd857AWyhSa3tPx3LPMmVpY6hartzNCEx2A-ApMk3dTVeocP-a72eHimZ0C1KcnwCcIWlkmz3gjNRKk887sUj7_R171Kw9DEG9QvmTaeD_Y_fvnAAkTABhV93MfazlepCfvffN89CGH4dGErhq_1pHGXJRd_9pdu4hayLS0MMic7SEzK0en9YvaXondX4EqkYHr8vMajdLqLCNm4LFMZ5sdNU_tT_qE-ahuN72bnEBJ9DbGlMkZScAI_dpWxQmJXFLtjcDxcwT8nPwbZo3PPf9CBedqiwBg1yy5m-9erSWSIK9CTqYkJlas3ChrChknDleBRTiqNZd-uPNNg=w718-h404-no"
      text:
        - paragraph: "Cette conf√©rence a pour but d'√™tre un lieu d'apprentissage et d'√©changes afin de progresser pour produire des logiciels toujours meilleurs."
    - title: "Se perfectionner"
      img: "https://lh3.googleusercontent.com/VBTPudAyF3aMlmZCQdbA5EdFRECVPNisG5UV54JGJxTgLVEyxdDHp_sfvf6wkY1a4l46g8LGMS0SfVwFie67M_3uZQeUDF_B6895k8zXrm1uJ0onnkc_OwVCj8dr6hKhXRMbY7NT6_beBjQDjhSQPlQm9nOULp0fWK5n6m9nrmf5h7Lo5IRkdueqZLHtlk4Jjafu2DgNiyRGGewl1RIp4P1n9guISsthYXkK63ujdYLXLHDvaQZIIVbgw4ecd1Lr-fF_smoXL65raKk8ucWPVvpl5iXuU37uzhjAd2Il_4RypVhuth609nEfH7h6fmbxMevOINVWtzc0O9eMdDSQ8waJloDXx-n1lZaPt3B1d1Qh3h9zR-0vNvgAq_mN8Y2Kp7tbSxCHB0chQt9Cjr7D8Tb7PAFj3GooccWx9lbCnCdkSxW7axs3UuXs-45lmEaOvt6cR3I46dRVUEp-T9KDXas3S8a7nym2CDy0yvrc65GR9M_oaiPsWQ9ZJjlZ_h-6-FxqBpeKLBl_7hVNSk69ydujV2G-VbwlhklkHvgfeCmeJqslQJAGiBAiRP7SJDc62K57jxSNzSncP6kUXpHasCncXFA_MTNYz-eSYVvd2M2_B-WZdLFwsKcfiK9ulG0gWYe5649-DRaFt6NQx1oJuI_9FZcddMZgiEctaKuu3mJViSjOqjVtvd5MSTyu3c7-tqZfqJyI1oKN40eglzUuhF0GHzbQNzsHlOArzKk4aNGm1KN3=w1247-h935-no"
      imgInRightSide: true
      text:
        - paragraph: "La conf√©rence est sur 2 jours : un jour sera d√©di√© aux personnes d√©sirant d√©couvrir de nouvelles pratiques et perfectionner leurs comp√©tences et un autre pour les pratiquants r√©guliers souhaitant approfondir leurs connaissances (en co-organisation avec <a href='https://socrates-fr.github.io/'' target='_blank'>SoCraTes-FR</a>)"

  # Location
  Location:
    - title: "Venir"
      text:
        - paragraph: >
                      Vous pouvez y acc√©der :
                      <ul class="lead">
                        <li>par les lignes de Bus Chrono 6, 12, 65 et 77, arr√™t "Grand Place"</li>
                        <li>par la ligne de Bus Chrono 3, arr√™t "Alpexpo"</li>
                        <li>en Tram par la Ligne A, arr√™t P√¥le Sud ‚Äì Alpexpo</li>
                        <li>en voiture, un grand parking gratuit est √† votre disposition en face de l‚Äôentr√©e</li>
                        <li>√† <a href="http://www.metromobilite.fr/velo.html" target="_blank"> v√©lo</a>, un parking sera √† votre disposition une fois pass√© les grilles</li>
                      </ul>

  # List of Sponsors
  Sponsors:
      - name: "Enalean"
        logo: "/img/sponsors/enalean.svg"
        url: "https://www.enalean.com/"
      - name: "Bonita"
        logo: "/img/sponsors/bonitasoft.png"
        url: "https://fr.bonitasoft.com/"
      - name: "Eloquant"
        logo: "/img/sponsors/eloquant.jpg"
        url: "https://www.eloquant.com/"
      - name: "Salesforce"
        logo: "/img/sponsors/salesforce.png"
        url: "https://www.salesforce.com"
      - name: "Zenika"
        logo: "/img/sponsors/zenika.png"
        url: "https://www.zenika.com/"

  # List of Partners
  Partners:
    - name: "AlpesJUG"
      logo: "/img/partners/alpesjug.png"
      url: "http://www.alpesjug.org/"
    - name: "CARA"
      logo: "/img/partners/cara.png"
      url: "http://grenoble.clubagilerhonealpes.org"
    - name: "SoCraTes-FR"
      logo: "/img/partners/SoCraTes-FR.jpg"
      url: "https://socrates-fr.github.io/"
    - name: "SNOWCAMP"
      logo: "/img/partners/snowcamp.png"
      url: "https://snowcamp.io/fr/"
#    - name: "Une petite mousse"
#      logo: "/img/partners/unepetitemousse.png"
#      url: "https://unepetitemousse.fr/"
    - name: "Copyright ¬© 2000-2022 JetBrains s.r.o. JetBrains and the JetBrains logo are registered trademarks of JetBrains s.r.o."
      logo: "/img/partners/jb_beam.png"
      url: "https://www.jetbrains.com/"
  SpeakersMap:
    sarahscarratt:
      name: "Sarah Scarratt"
      photo: "/img/speakers/sarah_scarratt.jpg"
      href: "https://www.linkedin.com/in/sarahscarratt2020"
#      text: "@SepNamdar"
#      company: "Soat"
      bio: "Sarah est une coach, mentor et formatrice certifi√©e, seule en France a √™tre sp√©cialis√©e dans le Clean Language et la mod√©lisation syst√©mique. Elle adore d√©couvrir comment les gens ¬´ fonctionnent ¬ª et se r√©jouit de les aider √† devenir curieux d'eux-m√™mes, sans porter de jugement. R√©v√©lant doucement les √©paisseurs jusqu'√† ce que nous trouvions un tr√©sor. Ou des d√©chets, auquel cas, on peut les transformer en ressource !

            Sarah dirige sa propre entreprise depuis 20 ans et poss√®de une vaste exp√©rience dans le recrutement et la formation, la gestion de petites entreprises ainsi que dans une vari√©t√© d'autres r√¥les tels que l'enseignement et l‚Äôaccompagnement en fin de vie."
    philippebourgau:
      name: "Philippe Bourgau"
      photo: "/img/logo/color/03-AlpesCraft_Couleurs-M.png"
      href: "https://www.linkedin.com/in/philippe-bourgau-607a928/?originalSubdomain=fr"
      #      text: "@SepNamdar"
      #      company: "Soat"
      bio: ""

  Schedule:
    - name: "Introduction au Clean Language"
      description: "Au cours de cet atelier interactif, nous explorerons le Clean Language et comment il peut √™tre utilis√© pour en savoir plus sur vous-m√™me et sur les autres afin de c√©l√©brer nos diff√©rences au lieu de r√©agir avec tensions et non-dits.
                    <br />
                    Les questions Clean ont √©t√© affin√©es au fil de nombreuses ann√©es et sont con√ßues pour permettre au coach d'√©viter d'ajouter ses propres pr√©suppos√©s ou jugements, et d'√©couter de fa√ßon exquise. Enseigner ces questions aux √©quipes les invite √† devenir curieux les uns des autres et √† ne plus d√©pendre du ScrumMaster ou du Coach Agile pour communiquer.
                    <br />
                    Le Clean Language est simple √† comprendre et difficile √† ma√Ætriser. Au cours de cette session, nous vous ferons utiliser les questions Clean et vous inviterons √† r√©fl√©chir √† la diff√©rence que cela pourrait faire si vous les utilisiez au travail (ou √† la maison !).  Il y aura d‚Äôautres ateliers vendredi selon la demande.
                    <br /><br />

                    Si vous souhaitez en savoir plus sur le Clean Language avant la session, ces deux liens vous aideront (en anglais)
                    <ul>
                      <li><a href=\"https://www.youtube.com/watch?v=aVvcU5gG4KU\">Caitlin Walker Tedx</a></li>
                      <li><a href=\"https://www.youtube.com/watch?v=_gSlRqfPT4E\">Qu'est-ce que la mod√©lisation syst√©mique</a></li>
                    </ul>
"
      type: "workshop"
      categories:
        - "Workshop"
        - "üí° Discovery"
#      date: "Mardi 08 Juin - 12h"
      language: "üá´üá∑"
      speakers:
        - speaker:
          speakerid: "sarahscarratt"

    - name: "Testez vos comp√©tences de refactoring sur la machine d'entrainement TCR !"
      description: "Que faites vous si votre entrainement devient trop facile? Ajoutez des poids! Peut-on faire cela avec des code katas?
                    <br/>
                    Le design incr√©mental consiste √† arr√™ter de penser au design comme grav√© dans le marbre, mais comme une infinit√© de petits pas. Maitriser les petit pas est un pr√©-requis pour le design incr√©mental. Mais comment enseigner les petits pas √† vos coll√®gues exp√©riment√©s qui se \"d√©brouillent\" pour r√©soudre un kata en une poign√©e de grands pas?
                    <br/>
                     TCR (test && commit || revert) est une machine d'entrainement au petits pas √† ajouter √† vos katas! En plus d'enseigner les petits pas, cet outil:
                    <br/>
                    <ul>
                       <li>est un coach qui rappel aux participants de prendre des petits pas</li>
                       <li>est moins √©nervant qu'un coach humain üòâ parce que ce n'est qu'un script!</li>
                       <li>est plus \"vendable\" que les katas de TDD, parce que ce n'est qu'un outil d'entrainement!</li>
                       <li>est amusant gr√¢ce √† sa touche de gamification</li>
                       <li>impacte directement votre programmation quotidienne, m√™me dans le code legacy, en enseignant la taille du pas qu'on est capable de faire sans erreur!</li>
                       <li>fonctionne parfaitement √† distance</li>
                     </ul>
                     <br/>
                     Rejoignez cette session, d√©couvrez TCR, pour enseigner le design incr√©mental √† votre √©quipe MAINTENANT!"
      type: "workshop"
      categories:
        - "Workshop"
        - "üí° Discovery"
        - "Beginner"
#      date: "Mardi 08 Juin - 13h"
      language: "üá´üá∑"
      speakers:
        - speaker:
          speakerid: "philippebourgau"